#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : petastorm
Version  : 0.9.8
Release  : 3
URL      : https://files.pythonhosted.org/packages/92/d0/9d8a28b3d45643e4fa7469e3409973603d299ceb3fb8a5a81fc4d06ea332/petastorm-0.9.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/92/d0/9d8a28b3d45643e4fa7469e3409973603d299ceb3fb8a5a81fc4d06ea332/petastorm-0.9.8.tar.gz
Summary  : Petastorm is a library enabling the use of Parquet storage from Tensorflow, Pytorch, and other Python-based ML training frameworks.
Group    : Development/Tools
License  : Apache-2.0
Requires: petastorm-bin = %{version}-%{release}
Requires: petastorm-python = %{version}-%{release}
Requires: petastorm-python3 = %{version}-%{release}
Requires: numpy
Requires: packaging
Requires: pandas
Requires: psutil
Requires: pyzmq
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : numpy
BuildRequires : packaging
BuildRequires : pandas
BuildRequires : psutil
BuildRequires : pyzmq
BuildRequires : six

%description
Petastorm
        =========

%package bin
Summary: bin components for the petastorm package.
Group: Binaries

%description bin
bin components for the petastorm package.


%package python
Summary: python components for the petastorm package.
Group: Default
Requires: petastorm-python3 = %{version}-%{release}

%description python
python components for the petastorm package.


%package python3
Summary: python3 components for the petastorm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the petastorm package.


%prep
%setup -q -n petastorm-0.9.8
cd %{_builddir}/petastorm-0.9.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609960031
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/petastorm-copy-dataset.py
/usr/bin/petastorm-generate-metadata.py
/usr/bin/petastorm-throughput.py

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
